version: '3.1'

services:
  db:
    image: postgres:14.4
    container_name: ordersdb
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ordersdb
    ports:
      - 5433:5432
    volumes:
      - .dbdata:/var/lib/postgresql/data
