version: '3.1'

services:
  db:
    image: postgres:14.4
    container_name: paymentsdb
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: paymentsdb
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/postgresql/data
